/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasswing;

import java.awt.event.ItemEvent;
import java.lang.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */
public class JFrameSwing extends javax.swing.JFrame {

    /**
     * Creates new form JFrameSwing
     */
    public JFrameSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelP = new javax.swing.JLabel();
        jLabelL = new javax.swing.JLabel();
        jLabelT = new javax.swing.JLabel();
        jTextP = new javax.swing.JTextField();
        jTextL = new javax.swing.JTextField();
        jTextT = new javax.swing.JTextField();
        jRadioLP = new javax.swing.JRadioButton();
        jRadioV = new javax.swing.JRadioButton();
        jLabelHL = new javax.swing.JLabel();
        jLabelHV = new javax.swing.JLabel();
        jButtonH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kalkulator Balok");

        jLabelP.setText("Panjang (cm)");

        jLabelL.setText("Lebar (cm)");

        jLabelT.setText("Tinggi (cm)");

        jTextP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPActionPerformed(evt);
            }
        });

        jRadioLP.setText("Luas Permukaan");
        jRadioLP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioLPActionPerformed(evt);
            }
        });

        jRadioV.setText("Volume");

        jLabelHL.setText("Hasil Luas: -----");

        jLabelHV.setText("Hasil Volume: -----");

        jButtonH.setText("Hitung");
        jButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 146, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonH)
                            .addComponent(jLabel1))
                        .addGap(163, 163, 163))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelHL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioLP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioV))
                                .addComponent(jLabelHV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelP)
                                    .addComponent(jLabelL)
                                    .addComponent(jLabelT))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextP, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(jTextL)
                                    .addComponent(jTextT))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelP)
                    .addComponent(jTextP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelL)
                    .addComponent(jTextL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelT)
                    .addComponent(jTextT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioLP)
                    .addComponent(jRadioV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelHL)
                .addGap(18, 18, 18)
                .addComponent(jLabelHV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonH)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPActionPerformed

    private void jRadioLPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioLPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioLPActionPerformed

    private void jButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHActionPerformed
        // TODO add your handling code here:
        try{
            String pString = jTextP.getText();
            String lString = jTextL.getText();
            String tString = jTextT.getText();
            
            Double panjang = Double.parseDouble(pString);
            Double lebar = Double.parseDouble(lString);
            Double tinggi = Double.parseDouble(tString);
            
            Double luasP = 2*panjang*lebar+2*panjang*tinggi+2*lebar*tinggi;
            Double volume = panjang * lebar * tinggi;
            
            if(jRadioLP.isSelected()){
                jLabelHL.setText("Hasil Luas: " + luasP + "cm^2");
            }
            else{
                jLabelHL.setText("Hasil Luas: -----");
            }
            
            if(jRadioV.isSelected()){
                jLabelHV.setText("Hasil Volume: " + volume + "cm^3");
            }
            else{
                jLabelHV.setText("Hasil Volume: -----");
            }
        } 
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Mohon Lengkapi Kolom dengan Menginput Angka!!");
        }
    }//GEN-LAST:event_jButtonHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrameSwing().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelHL;
    private javax.swing.JLabel jLabelHV;
    private javax.swing.JLabel jLabelL;
    private javax.swing.JLabel jLabelP;
    private javax.swing.JLabel jLabelT;
    private javax.swing.JRadioButton jRadioLP;
    private javax.swing.JRadioButton jRadioV;
    private javax.swing.JTextField jTextL;
    private javax.swing.JTextField jTextP;
    private javax.swing.JTextField jTextT;
    // End of variables declaration//GEN-END:variables
}
